ICE:
  occurrence: 0.6
  science_value: 0.1
  color: {r: 125, g: 217, b: 255}
  density: 997 # kg/m^3

SALT_ICE:
  occurrence: 0.3
  science_value: 0.6
  color: {r: 204, g: 204, b: 255}
  density: 0

SALT:
  occurrence: 0.1
  science_value: 0.1
  color: {r: 231, g: 231, b: 245}
  density: 0

