# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: default_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - j_ant_pan
    - j_ant_tilt
    - j_shou_yaw
    - j_shou_pitch
    - j_prox_pitch
    - j_dist_pitch
    - j_hand_yaw
    - j_grinder
    - j_scoop_yaw
  sim_control_mode: 1  # 0: position, 1: velocity
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - j_shou_yaw
      - j_shou_pitch
      - j_prox_pitch
      - j_dist_pitch
      - j_hand_yaw
      - j_scoop_yaw
  # TODO: We probably need to move the grinder_controller to another file to
  # ease the process of controller switching
  # - name: grinder_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   joints:
  #     - j_shou_yaw
  #     - j_shou_pitch
  #     - j_prox_pitch
  #     - j_dist_pitch
  #     - j_hand_yaw
  #     - j_grinder
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j_shou_yaw
    - j_shou_pitch
    - j_prox_pitch
    - j_dist_pitch
    - j_hand_yaw
    - j_scoop_yaw
  gains:
    j_shou_yaw: 
      p: &kp_default 16000
      d: &kd_default 5.0
      i: &ki_default 2
      i_clamp: &ki_clamp_default 1
    j_shou_pitch:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_prox_pitch:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_dist_pitch:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_hand_yaw:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_scoop_yaw:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    constraints:
      goal_time: &goal_time_constraint 4.0
      stopped_velocity_tolerance: 0
      j_shou_yaw: {trajectory: &goal_pos_constraint 0.5, goal: &trajectory_pos_constraint 1.0}
      j_shou_pitch: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
      j_prox_pitch: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
      j_dist_pitch: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
      j_hand_yaw: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
      j_scoop_yaw: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
    stop_trajectory_duration: 1.0
limbs_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j_shou_yaw
    - j_shou_pitch
    - j_prox_pitch
    - j_dist_pitch
    - j_hand_yaw
  gains:
    j_shou_yaw:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_shou_pitch:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_prox_pitch:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_dist_pitch:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_hand_yaw:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    constraints:
      goal_time: *goal_time_constraint
      stopped_velocity_tolerance: 0
      j_shou_yaw: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
      j_shou_pitch: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
      j_prox_pitch: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
      j_dist_pitch: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
      j_hand_yaw: {trajectory: *goal_pos_constraint, goal: *trajectory_pos_constraint}
    stop_trajectory_duration: 1.0
grinder_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j_shou_yaw
    - j_shou_pitch
    - j_prox_pitch
    - j_dist_pitch
    - j_hand_yaw
    - j_grinder
  gains:
    j_shou_yaw:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_shou_pitch:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_prox_pitch:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_dist_pitch:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_hand_yaw:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
    j_grinder:
      p: *kp_default
      d: *kd_default
      i: *ki_default
      i_clamp: *ki_clamp_default
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 300
ant_pan_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_ant_pan
  pid: {p: 100.0, i: 0.01, d: 15.0}
ant_tilt_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_ant_tilt
  pid: {p: 550.0, i: 0.01, d: 70.0}